"""asd

Revision ID: 01597ea8be0f
Revises: 3864b1fd7a7a
Create Date: 2024-04-26 17:33:56.091513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01597ea8be0f'
down_revision = '3864b1fd7a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
