"""asd

Revision ID: 246310245841
Revises: a4bbedb762c4
Create Date: 2024-04-27 15:51:48.885225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246310245841'
down_revision = 'a4bbedb762c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
