"""sad

Revision ID: 2ffd53e38fa0
Revises: 1698d721ff74
Create Date: 2024-04-27 13:57:02.332774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffd53e38fa0'
down_revision = '1698d721ff74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_news_id_fkey', type_='foreignkey')
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_news_id_fkey', 'news', ['news_id'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
