"""asd

Revision ID: 3864b1fd7a7a
Revises: b05817b69798
Create Date: 2024-04-26 17:28:55.106315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3864b1fd7a7a'
down_revision = 'b05817b69798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_addtime'), ['addtime'], unique=False)

    op.create_table('new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=120), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_new_addtime'), ['addtime'], unique=False)

    op.drop_table('product_promotions')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index('ix_promotions_end_date')
        batch_op.drop_index('ix_promotions_start_date')

    op.drop_table('promotions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('promotions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prices', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='promotions_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('ix_promotions_start_date', ['start_date'], unique=False)
        batch_op.create_index('ix_promotions_end_date', ['end_date'], unique=False)

    op.create_table('product_promotions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promotion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_promotions_product_id_fkey'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], name='product_promotions_promotion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_promotions_pkey')
    )
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_new_addtime'))

    op.drop_table('new')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_addtime'))

    op.drop_table('author')
    # ### end Alembic commands ###
