"""asd

Revision ID: 431813c62802
Revises: d9eaba284c7d
Create Date: 2024-04-26 17:39:45.526651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431813c62802'
down_revision = 'd9eaba284c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
