"""all new 2

Revision ID: 4a5aba2293ba
Revises: f3232ce3fb20
Create Date: 2024-04-22 18:25:39.228085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5aba2293ba'
down_revision = 'f3232ce3fb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_cart_addtime')
        batch_op.drop_constraint('cart_product_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_foreign_key('cart_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.create_index('ix_cart_addtime', ['addtime'], unique=False)
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
