"""all new 4

Revision ID: 592e8d5be498
Revises: 562b0a887d01
Create Date: 2024-04-22 18:30:53.245327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592e8d5be498'
down_revision = '562b0a887d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('number')

    # ### end Alembic commands ###
