"""12345679

Revision ID: 621a84481aeb
Revises: 89385773df26
Create Date: 2024-04-25 17:36:02.835837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621a84481aeb'
down_revision = '89385773df26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storeinventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storeinventory_addtime'), ['addtime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storeinventory_addtime'))

    op.drop_table('storeinventory')
    # ### end Alembic commands ###
