"""1234567901

Revision ID: 637124cabb83
Revises: a2836eb80924
Create Date: 2024-04-25 20:22:23.667344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '637124cabb83'
down_revision = 'a2836eb80924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=140), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.drop_index('ix_storeinventory_addtime')

    op.drop_table('storeinventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storeinventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('addtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='storeinventory_product_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='storeinventory_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='storeinventory_pkey')
    )
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.create_index('ix_storeinventory_addtime', ['addtime'], unique=False)

    op.drop_table('reviews')
    op.drop_table('inventory')
    op.drop_table('discount')
    # ### end Alembic commands ###
