"""123456

Revision ID: 758a0ce76b15
Revises: aad489647f9d
Create Date: 2024-04-25 14:39:41.612667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758a0ce76b15'
down_revision = 'aad489647f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_cat_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sub_cat_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('product_supercat_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('product_subcat_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'supercat', ['super_cat_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcat', ['sub_cat_id'], ['id'])
        batch_op.drop_column('subcat_id')
        batch_op.drop_column('supercat_id')

    with op.batch_alter_table('subcat', schema=None) as batch_op:
        batch_op.alter_column('cat_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('super_cat_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('supercat', schema=None) as batch_op:
        batch_op.alter_column('cat_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supercat', schema=None) as batch_op:
        batch_op.alter_column('cat_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('subcat', schema=None) as batch_op:
        batch_op.alter_column('super_cat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cat_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supercat_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subcat_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_subcat_id_fkey', 'subcat', ['subcat_id'], ['id'])
        batch_op.create_foreign_key('product_supercat_id_fkey', 'supercat', ['supercat_id'], ['id'])
        batch_op.drop_column('sub_cat_id')
        batch_op.drop_column('super_cat_id')

    # ### end Alembic commands ###
