"""12345679

Revision ID: 947f9175fddf
Revises: 9bc5b45d2843
Create Date: 2024-04-25 17:38:18.028415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947f9175fddf'
down_revision = '9bc5b45d2843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('storeinventory_Shop_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop', ['shop_id'], ['id'])
        batch_op.drop_column('Shop_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('storeinventory_Shop_id_fkey', 'shop', ['Shop_id'], ['id'])
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
