"""12345679

Revision ID: 9bc5b45d2843
Revises: 621a84481aeb
Create Date: 2024-04-25 17:36:28.600403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc5b45d2843'
down_revision = '621a84481aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Shop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shop', ['Shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storeinventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Shop_id')

    # ### end Alembic commands ###
