"""123456790

Revision ID: a2836eb80924
Revises: 947f9175fddf
Create Date: 2024-04-25 18:20:07.242673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2836eb80924'
down_revision = '947f9175fddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('order_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_detail', schema=None) as batch_op:
        batch_op.drop_column('order_name')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
