"""asd

Revision ID: a4bbedb762c4
Revises: 
Create Date: 2024-04-27 15:24:44.232677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4bbedb762c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('ix_news_addtime')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_news_id_fkey', type_='foreignkey')
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_news_id_fkey', 'news', ['news_id'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index('ix_news_addtime', ['addtime'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='comment_news_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='comment_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    # ### end Alembic commands ###
