"""test 6

Revision ID: c613f82f236d
Revises: 
Create Date: 2024-04-23 12:51:37.012749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c613f82f236d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recevie_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recevie_tel', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(length=255), nullable=True))
        batch_op.alter_column('recevie_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('recevie_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('remark')
        batch_op.drop_column('recevie_tel')
        batch_op.drop_column('recevie_address')

    # ### end Alembic commands ###
