"""asd

Revision ID: d4dd0bd5beee
Revises: dc15ff1808e1
Create Date: 2024-04-26 22:01:44.914163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4dd0bd5beee'
down_revision = 'dc15ff1808e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=120), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_addtime'), ['addtime'], unique=False)

    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.drop_index('ix_new_addtime')

    op.drop_table('new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='new_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='new_pkey')
    )
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.create_index('ix_new_addtime', ['addtime'], unique=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_addtime'))

    op.drop_table('news')
    # ### end Alembic commands ###
