"""asd

Revision ID: dc15ff1808e1
Revises: 350b8d098913
Create Date: 2024-04-26 21:49:48.918797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc15ff1808e1'
down_revision = '350b8d098913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
