"""all new 2

Revision ID: 271b416f97af
Revises: 7349791266ec
Create Date: 2024-04-22 17:34:21.290335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271b416f97af'
down_revision = '7349791266ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('ix_cart_addtime')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('orders_detail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('addtime', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_addtime'), ['addtime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_addtime'))
        batch_op.drop_column('addtime')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('orders_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_cart_addtime', ['addtime'], unique=False)

    # ### end Alembic commands ###
