"""all new 1 

Revision ID: 7349791266ec
Revises: 
Create Date: 2024-04-22 15:45:46.185389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7349791266ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=120), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Product_addtime'), ['addtime'], unique=False)

    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collect_addtime'), ['addtime'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recevie_name', sa.String(length=255), nullable=True),
    sa.Column('recevie_address', sa.String(length=255), nullable=True),
    sa.Column('recevie_tel', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_addtime'), ['addtime'], unique=False)

    op.create_table('orders_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_item')
    op.drop_table('product')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('addtime', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cart_addtime'), ['addtime'], unique=False)
        batch_op.create_foreign_key(None, 'Product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cart_addtime'))
        batch_op.drop_column('addtime')
        batch_op.drop_column('number')
        batch_op.drop_column('user_id')
        batch_op.drop_column('product_id')
        batch_op.drop_column('id')

    op.create_table('product',

    )
    op.create_table('cart_item',

    )
    op.drop_table('orders_detail')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_addtime'))

    op.drop_table('orders')
    with op.batch_alter_table('collect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collect_addtime'))

    op.drop_table('collect')
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Product_addtime'))

    op.drop_table('Product')
    # ### end Alembic commands ###
